field: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
fieldLayouts:
  4f4ed56c-1fee-4168-801f-70ad11dbe0d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 68c36b78-e56c-45f0-90a2-b93ccc0f1ee6 # Rich Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9a10396-11e9-4c6f-b28b-bc60e30a3000
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ab7943e-e0be-449b-af79-0c80d3182846
        userCondition: null
fields:
  68c36b78-e56c-45f0-90a2-b93ccc0f1ee6: # Rich Text
    columnSuffix: sfzbmatj
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: null
    name: 'Rich Text'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 2
