field: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
fieldLayouts:
  f649ca5e-b204-4bd5-af75-286151f975dd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 33001227-43a9-4c08-8a5c-5e8bf0e4e3ac # Markup
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3db8a18-536a-4996-8417-b6f6f9b0ecd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0867b698-544b-437e-95b4-05186f225d43
        userCondition: null
fields:
  33001227-43a9-4c08-8a5c-5e8bf0e4e3ac: # Markup
    columnSuffix: trmcykfn
    contentColumnType: text
    fieldGroup: null
    handle: markup
    instructions: null
    name: Markup
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: embedCode
name: 'Embed Code'
sortOrder: 5
