field: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
fieldLayouts:
  6c07c85b-3229-42fe-a6df-9b905ad7c243:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d08e6f3-ae71-4a17-a1f5-97abeb7193f9 # Blog Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9aaf9382-7cfe-4e14-baf5-0b5ff5f5e202
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d99087f8-d76e-43c8-86f5-afc78b3f4430 # No Transform
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aadab461-22e3-4473-a681-ab14e0fe878e
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: e0270692-1ca3-4ba6-8d52-cfca54ac634a # Size
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8abe46ae-628c-4f71-9268-d707f5ab4d34
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a070ee30-4cf4-4a25-8bb8-7768d85f66f7 # Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23dbf577-fd5c-4616-a91c-a2fb07aa4cf6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 82e0e8c4-4d0e-4fc4-83f5-1a60298d9dcc # Margins
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b9889d7-1bb4-41a8-9ca4-25beccda29f5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1c1054c9-4810-4918-b3c1-3bd0d6a13675 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 935b4c4a-7762-4cc5-b83a-2a004805395f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 26e93876-a78a-402d-b49e-a55f7d4e5374 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 463a190e-9b2b-46c6-8afc-6cf3c4477d65
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 763c3c27-d89d-4fc6-ac15-ab0e8b3fbd37
        userCondition: null
fields:
  1c1054c9-4810-4918-b3c1-3bd0d6a13675: # Caption
    columnSuffix: kgnvuymj
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2d08e6f3-ae71-4a17-a1f5-97abeb7193f9: # Blog Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blogImage
    instructions: null
    name: 'Blog Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:c1052de8-6217-41e9-8c24-2b4da3d48b10' # Blog Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c1052de8-6217-41e9-8c24-2b4da3d48b10' # Blog Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  26e93876-a78a-402d-b49e-a55f7d4e5374: # Link URL
    columnSuffix: krukznax
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: null
    name: 'Link URL'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  82e0e8c4-4d0e-4fc4-83f5-1a60298d9dcc: # Margins
    columnSuffix: nyiemkxc
    contentColumnType: string
    fieldGroup: null
    handle: margins
    instructions: null
    name: Margins
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Top Margin'
            -
              - value
              - top-margin
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Margin'
            -
              - value
              - bottom-margin
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top & Bottom Margin'
            -
              - value
              - 'top-margin bottom-margin'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a070ee30-4cf4-4a25-8bb8-7768d85f66f7: # Background
    columnSuffix: bqwqvusk
    contentColumnType: text
    fieldGroup: null
    handle: background
    instructions: null
    name: Background
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d99087f8-d76e-43c8-86f5-afc78b3f4430: # No Transform
    columnSuffix: zmtpeewv
    contentColumnType: boolean
    fieldGroup: null
    handle: noTransform
    instructions: null
    name: 'No Transform'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e0270692-1ca3-4ba6-8d52-cfca54ac634a: # Size
    columnSuffix: ncvbdlpf
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: size
    instructions: null
    name: Size
    searchable: false
    settings:
      decimals: 0
      defaultValue: 100
      max: 100
      min: 1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: image
name: Image
sortOrder: 3
