field: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
fieldLayouts:
  0b1cf13f-23a0-4104-9ec8-e18046ded0e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3f0e0a64-f0b3-42c2-b38a-3bd34bf15cb4 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22816e1a-471e-417c-ab9a-11e76cf016eb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9ea32fa5-e1b5-4900-96a6-86c01b8dbc68 # Subheadline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c91b1eff-0402-4c5e-b70e-19dc09231e04
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7517c439-55f4-420f-9514-cad4d205f293 # Alternate TOC Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef2dc748-c9ab-45b5-83db-7aca2065b9d2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9b6b4041-451d-480f-bfb4-9116294162ad # Blog Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92b9746a-6b5a-46f4-bdcd-04de975429f8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d30b8ce1-04a4-4e95-a1e6-570d2e4f339f # No Transform
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fa32bdb-5405-4be9-8434-6e142132ebf9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6c48f2a4-30de-4d42-a211-268e766bd9b1 # Size
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88f4edb1-f1d9-46d2-b639-48ac6761d4db
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 055b60fb-8617-44d9-aa31-c628008126b0 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 742a1a3e-4d71-45d6-a10c-de161b1dc1f2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7753be54-298e-490f-9ab3-381c71785210 # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f89fc82-4995-46ba-a633-1f527e6c9041
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 555e19eb-df0c-48bc-b4b9-bdc423af2204 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe2ceaa0-6184-4f90-9ac0-8bcb2292989b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d49894c-7b89-485b-a00d-c6782a84e522
        userCondition: null
fields:
  3f0e0a64-f0b3-42c2-b38a-3bd34bf15cb4: # Headline
    columnSuffix: vwcuikgm
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6c48f2a4-30de-4d42-a211-268e766bd9b1: # Size
    columnSuffix: fapcidau
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: size
    instructions: null
    name: Size
    searchable: false
    settings:
      decimals: 0
      defaultValue: 100
      max: 100
      min: 1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  9b6b4041-451d-480f-bfb4-9116294162ad: # Blog Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blogImage
    instructions: null
    name: 'Blog Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:c1052de8-6217-41e9-8c24-2b4da3d48b10' # Blog Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c1052de8-6217-41e9-8c24-2b4da3d48b10' # Blog Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9ea32fa5-e1b5-4900-96a6-86c01b8dbc68: # Subheadline
    columnSuffix: qqkscykb
    contentColumnType: text
    fieldGroup: null
    handle: subheadline
    instructions: null
    name: Subheadline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  055b60fb-8617-44d9-aa31-c628008126b0: # Caption
    columnSuffix: nabiyubb
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  555e19eb-df0c-48bc-b4b9-bdc423af2204: # Rich Text
    columnSuffix: wotzdkmm
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: null
    name: 'Rich Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: cc64f857-3e97-42d7-8a16-79223c695a98 # Default
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: true
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  7517c439-55f4-420f-9514-cad4d205f293: # Alternate TOC Text
    columnSuffix: yseuvkoe
    contentColumnType: text
    fieldGroup: null
    handle: alternateTocText
    instructions: null
    name: 'Alternate TOC Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7753be54-298e-490f-9ab3-381c71785210: # Link URL
    columnSuffix: mlehtxum
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: null
    name: 'Link URL'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d30b8ce1-04a4-4e95-a1e6-570d2e4f339f: # No Transform
    columnSuffix: etzinoqo
    contentColumnType: boolean
    fieldGroup: null
    handle: noTransform
    instructions: null
    name: 'No Transform'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: imageText
name: 'Image & Text'
sortOrder: 4
