field: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
fieldLayouts:
  77b6799b-9d26-43ec-8d71-67d7262e1650:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cd4a38c4-94ce-4c20-9d8b-62288944ef87 # Media Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8cba6eb-3a13-46a5-a516-eba19c972454
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5eff53ba-9583-4e3e-92ce-d1d630f3f363 # Media ID
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e959dae5-2795-47aa-86b2-b9ca2965eea3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 67862bf2-294a-4e45-af45-324c297cbea8 # Minute Mark
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8220b926-b3e6-4e57-adb2-22f8eb60fe27
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: de2bb280-3465-478f-a8b2-bb03f3c7be35 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5b64367-d4d7-4e1d-8c49-64687153306a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e4f5e34-13f8-422b-bcd3-f2aca3653926
        userCondition: null
fields:
  5eff53ba-9583-4e3e-92ce-d1d630f3f363: # Media ID
    columnSuffix: tdfbfjnp
    contentColumnType: text
    fieldGroup: null
    handle: mediaId
    instructions: null
    name: 'Media ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  67862bf2-294a-4e45-af45-324c297cbea8: # Minute Mark
    columnSuffix: xlyfqclg
    contentColumnType: text
    fieldGroup: null
    handle: minuteMark
    instructions: null
    name: 'Minute Mark'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'in seconds (i.e. "264" for 4:24)'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cd4a38c4-94ce-4c20-9d8b-62288944ef87: # Media Type
    columnSuffix: mgglwxhu
    contentColumnType: string(9)
    fieldGroup: null
    handle: mediaType
    instructions: null
    name: 'Media Type'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - YouTube
            -
              - value
              - youtube
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Instagram
            -
              - value
              - instagram
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  de2bb280-3465-478f-a8b2-bb03f3c7be35: # Caption
    columnSuffix: mxaotbsv
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: media
name: Media
sortOrder: 4
