field: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
fieldLayouts:
  32ff5fa9-ae86-43ff-a044-23279a1bb95f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ee13e705-afd8-41c1-a111-b472a62a15f2 # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc4157cf-46ba-43de-8c9b-a98188566f38
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acdcd6cb-c200-42d3-a723-ea131a1387dd # Subheadline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41349afd-2468-4919-bf14-364f7ef8932a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c4d8031-9950-49c3-9f52-6a52a2cdfb94
        userCondition: null
fields:
  acdcd6cb-c200-42d3-a723-ea131a1387dd: # Subheadline
    columnSuffix: ndhscpec
    contentColumnType: text
    fieldGroup: null
    handle: subheadline
    instructions: null
    name: Subheadline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ee13e705-afd8-41c1-a111-b472a62a15f2: # Headline
    columnSuffix: gjehwrup
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sectionTitle
name: 'Section Title'
sortOrder: 1
