field: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
fieldLayouts:
  77b6799b-9d26-43ec-8d71-67d7262e1650:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5eff53ba-9583-4e3e-92ce-d1d630f3f363 # YouTube ID
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e959dae5-2795-47aa-86b2-b9ca2965eea3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: de2bb280-3465-478f-a8b2-bb03f3c7be35 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5b64367-d4d7-4e1d-8c49-64687153306a
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 9e4f5e34-13f8-422b-bcd3-f2aca3653926
        userCondition: null
fields:
  5eff53ba-9583-4e3e-92ce-d1d630f3f363: # YouTube ID
    columnSuffix: tdfbfjnp
    contentColumnType: text
    fieldGroup: null
    handle: youtubeId
    instructions: null
    name: 'YouTube ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  de2bb280-3465-478f-a8b2-bb03f3c7be35: # Caption
    columnSuffix: mxaotbsv
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: video
name: Video
sortOrder: 4
