columnSuffix: tyoweuik
contentColumnType: text
fieldGroup: fa511e02-7c6f-4081-9701-b14c76ecf31a # Common
handle: fullName
instructions: null
name: 'Full Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
