columnSuffix: mmlrtbal
contentColumnType: boolean
fieldGroup: fa511e02-7c6f-4081-9701-b14c76ecf31a # Common
handle: show
instructions: null
name: Show
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
