columnSuffix: mskyifeo
contentColumnType: boolean
fieldGroup: fa511e02-7c6f-4081-9701-b14c76ecf31a # Common
handle: showImageCarousel
instructions: null
name: 'Show Image Carousel'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
