fieldLayouts:
  3a7388a5-e7a2-46e9-9359-051e73f182dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e8d42f4b-c24c-435c-9cba-2b05fb0c9e5d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2075787e-20ab-458f-81df-dd47b726a51b # Show
            instructions: null
            label: 'Show In Menu'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d281821b-86f7-421e-b903-f1e2cefd0f19
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1b12d4c8-a449-4b45-99db-cdcf801d8fa4 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f445c537-24de-4778-9b31-3c29ee4b8728
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed962f96-407c-48ee-9fe2-daccbb4b7a16 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c4d86a2-6ae1-4822-bca8-ca917c2f5d42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7338fd63-9ce2-4696-a9b3-113b5d6015c3 # Subheadline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 303d3ffc-abc7-4b39-a7e5-952fe478d295
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d9d41d0-9e17-402e-8e87-a5d4346dce47 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 226070ac-2389-4ae5-a423-49748328d90e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc1e02e0-fca6-4960-ba63-8036f932aeb0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac112358-b098-4b74-b9fe-763ece5d27e0 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9921afb3-60ec-4a30-acfb-7110bb528830
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e55684f7-379f-42d4-8c46-0d4bca63ecee # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56a8e497-8a19-42b9-b93c-d4a3dc7d6c9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a780297-6f26-445e-ab9a-59602ffc5dbc # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1712f977-309d-4817-94fe-e7f606bcc550
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 293b000e-9f7f-4c40-bc3c-3f2c1a1d2950
        userCondition: null
handle: decade
hasTitleField: true
name: Decade
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
