fieldLayouts:
  705149bd-e05b-41c7-94b8-f3e0253ba2c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a5f8367-c8cf-4a93-ad10-1e3d96f2656c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 2075787e-20ab-458f-81df-dd47b726a51b # Show
            instructions: null
            label: 'Show In Menu'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d684a2d0-5d7c-4a8e-b6ce-7bfcee2d6d30
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9d9d41d0-9e17-402e-8e87-a5d4346dce47 # Short Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd3ffccd-443f-4e1c-9029-3e1d9d6594c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8738dbd4-2302-4215-b0a0-84158c48a9ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e55684f7-379f-42d4-8c46-0d4bca63ecee # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93844c9a-959d-41dd-9ecb-aeb20ef3e4e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a780297-6f26-445e-ab9a-59602ffc5dbc # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ddff141-8497-4f42-a8bc-5866976e847f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 0f138e01-eddc-4fef-b078-5f2fa151e0e7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 04623371-fa0e-4ff7-84f9-93dcf4e31080 # Category
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
