fieldLayouts:
  5ac791f4-32d4-43cb-9aa2-aac5e9e2a9ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4916cd3d-088c-4f0b-ba2e-f3b637c075d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37ff1ae6-ced2-4eaf-b107-93e6e3dd94be # Band Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bc98d7c-1658-42d3-9b0f-b57a92e13a37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d9d41d0-9e17-402e-8e87-a5d4346dce47 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20b1e63a-458f-40bd-a857-c577ab09d1a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4dd1da95-0072-47a9-90fb-2b0a3b7c3936
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 2ee0929d-42ad-44ca-9f6a-990c73c36c1c # Bands
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
