fieldLayouts:
  40a0ed60-feca-4039-a161-5359d4696aaf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 41bfe45d-cce7-4552-8980-31e27bf3f2d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7338fd63-9ce2-4696-a9b3-113b5d6015c3 # Subheadline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8268ad22-a6fc-4aa2-ab38-a001678a3e60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d9d41d0-9e17-402e-8e87-a5d4346dce47 # Short Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d515152-04b3-463c-be88-ac1a3afb71b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fab3405a-11f1-4389-b8fb-d7f3fae15087 # Featured Snippet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 834eef4a-9a3d-4444-8fb5-a0708cc28e6d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Featured Image'
            type: craft\fieldlayoutelements\Heading
            uid: df728a30-d337-40f8-887e-739b4de6a07d
            userCondition: null
          -
            elementCondition: null
            fieldUid: 80a9c5e0-fb80-420c-a7df-676f56ac600d # Blog Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba6a4efe-03f0-449a-a395-478856d248f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Blog Info'
            type: craft\fieldlayoutelements\Heading
            uid: f43b26a5-5e0c-4422-a640-ad004052b6cf
            userCondition: null
          -
            elementCondition: null
            fieldUid: a47603f2-0b4e-42c5-9f37-84cc7ceac8f0 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b0bdf4e-9108-4542-9687-886f5bef0a22
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7149d8a6-d74b-4e10-b59b-80f37708aaa0 # TOC Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d8c4b0e-4681-464a-8fb8-e59f17af0d30
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b5c7b937-2d08-4b03-a22e-83f2879773fe # TOC Default
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a0af5f7-aae5-4a31-b168-27ada2d5308f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b7ec030d-fd66-4c86-be9c-5cec826a7638 # Change
            instructions: null
            label: 'Ordered Section Titles'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87a97a14-f2be-4407-902c-aa8099629d91
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            heading: Writer
            type: craft\fieldlayoutelements\Heading
            uid: 71ad2d2d-36ba-49c5-ae8e-3bd5fe1e60be
            userCondition: null
          -
            elementCondition: null
            fieldUid: f85c3fd3-04eb-4069-a712-f8725e5c5fac # Full Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9655082-86b0-4739-af16-6b2b74d792b2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e1e2658d-253a-4426-b447-fce24b18410a # Website URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df968df8-0537-4aa8-a90e-91eb54d0ef8e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 24792e71-a84c-4970-acf7-c69480e02e11 # Writer Picture
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af58e8f2-957a-4cd0-99bf-60cc44a30c43
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: 0d9d097a-76ac-4c93-afff-b2e2dff7cffc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9a6940a2-21f7-479b-89de-7b12ff94ad18 # Long Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaa56d3d-22a9-4a57-a271-c6344097e913
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 266355e1-d1f3-4d71-a92d-2d3a714c3d06 # Blog Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 226b85bb-85bb-4e30-b0f0-aa1a9c697f10
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5fc129c5-9ac6-4300-8212-a243610269d0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac112358-b098-4b74-b9fe-763ece5d27e0 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 627674bf-10e6-49cb-8b24-78f5808c8bed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e55684f7-379f-42d4-8c46-0d4bca63ecee # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4c81f00-1018-40d3-b538-bb880ea86af1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a780297-6f26-445e-ab9a-59602ffc5dbc # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2defd6b4-b6db-46d0-b4bc-a54658ca63e6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9fb102dd-839a-4229-82ce-229ed6669f92 # Optimized
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b7d57a1-5583-460e-971c-cf16de168e75
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            heading: 'SEO Keywords'
            type: craft\fieldlayoutelements\Heading
            uid: f95ed532-69c8-4d93-bba8-1c9b0a28a790
            userCondition: null
          -
            elementCondition: null
            fieldUid: cdaef71d-1a83-462b-92b2-4d96fd8d8b32 # Related SEO Keywords
            instructions: null
            label: 'Related Keywords'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b47a8fb-70f3-424a-97cb-7ec02d04eecd
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2707b5e8-15c9-45e5-a8dc-36947636f8a0
        userCondition: null
handle: dynamic
hasTitleField: true
name: Dynamic
section: ed3ddcd0-5218-490f-a4b7-d5000594dcf2 # Blog Post
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
