color: blue
fieldLayouts:
  f649ca5e-b204-4bd5-af75-286151f975dd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0e1a1926-4fc8-4fde-a15a-cb4bdb6dcf45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 240b171c-f828-4004-ab96-26ec79e03694 # Blog Content - Embed Code - Figure Type
            handle: null
            includeInCards: true
            instructions: null
            label: 'Figure Type'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdeb06ac-c95f-49ed-a326-f039ea04c4ba
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8297f5ab-0624-4ef9-bdba-8bef1cc43523 # Blog Content - Embed Code - Figure Caption
            handle: null
            includeInCards: false
            instructions: null
            label: 'Figure Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 302a5236-991b-4a5e-9cc5-2e7b1fec7f1d
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 33001227-43a9-4c08-8a5c-5e8bf0e4e3ac # Blog Content - Embed Code - Markup
            handle: null
            includeInCards: false
            instructions: null
            label: Markup
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3db8a18-536a-4996-8417-b6f6f9b0ecd9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0867b698-544b-437e-95b4-05186f225d43
        userCondition: null
handle: embedCode
hasTitleField: false
icon: code
name: 'Embed Code'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
