fieldLayouts:
  f4e9f35b-1da7-4db6-93c2-6635e16c301d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bd8117f1-e204-40a3-9c43-b99816edf317
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a5ed287-36a7-4e22-86fb-1288e0690e35
        userCondition: null
handle: epk
hasTitleField: true
name: EPK
section: 651d957a-7941-45d8-8585-8f63b71d5320 # EPK
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
