fieldLayouts:
  b54d0a7b-89cd-4619-b613-01976ef85db4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 80d3f49f-9dcb-4460-aa97-e7c3283c7732
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7338fd63-9ce2-4696-a9b3-113b5d6015c3 # Subheadline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 692a110e-97d3-486b-b12d-26f38430840d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d9d41d0-9e17-402e-8e87-a5d4346dce47 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73a73a62-3004-4169-b445-49b0327bfcd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1e2658d-253a-4426-b447-fce24b18410a # Website URL
            instructions: null
            label: 'Article URL'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4583e762-8ba8-4b0a-8992-10301657a53d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a47603f2-0b4e-42c5-9f37-84cc7ceac8f0 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab47e7e3-87db-4328-bdff-8d86b82820eb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 80a9c5e0-fb80-420c-a7df-676f56ac600d # Blog Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12e9a483-9145-4924-a7af-0630527ef596
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f663d014-30ef-4783-b5bd-8c974833fe36 # Opacity
            instructions: null
            label: 'Image Opacity'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dfbe73d-6000-413d-be53-515816e5db89
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            heading: Writer
            type: craft\fieldlayoutelements\Heading
            uid: c408f54d-7bfd-47be-b20b-768e551c5cd9
            userCondition: null
          -
            elementCondition: null
            fieldUid: f85c3fd3-04eb-4069-a712-f8725e5c5fac # Full Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce2405fb-93ca-4962-bee0-030a37940194
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 24792e71-a84c-4970-acf7-c69480e02e11 # Writer Picture
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05e6af21-e8c3-47d0-a18e-257e07ca16df
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: e989f0fb-5e7d-4510-97da-f3300bcaf1f4
        userCondition: null
handle: external
hasTitleField: true
name: External
section: ed3ddcd0-5218-490f-a4b7-d5000594dcf2 # Blog Post
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
