fieldLayouts:
  f8cafe80-f4a2-44b3-9442-2242ec5de30d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa695c7f-248d-495c-a8c6-138ec3633264
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 67f925c7-9b91-4a95-b700-1b99ee38057f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e55684f7-379f-42d4-8c46-0d4bca63ecee # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7852defc-9888-452e-8535-4d7f4d7570b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a780297-6f26-445e-ab9a-59602ffc5dbc # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d31e5458-1229-4a16-ab66-1e0f3fb952f6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e7651b06-b1bb-453f-857b-e90fb27deca7
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: eb6cec15-707d-4542-8311-cb925d61ee30 # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
