color: null
fieldLayouts:
  f8cafe80-f4a2-44b3-9442-2242ec5de30d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa695c7f-248d-495c-a8c6-138ec3633264
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 8bb43633-4a68-4f44-93b1-84ef2584a366 # CTA Text 2
            handle: null
            includeInCards: false
            instructions: null
            label: 'Popular Articles (mobile headline~desktop headline)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4627ae5e-a9e4-4c6d-87e4-49ad6a9d8f9a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2075787e-20ab-458f-81df-dd47b726a51b # Show
            handle: null
            includeInCards: false
            instructions: null
            label: 'Show CTA'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daa7254f-0111-468e-98a4-b17dd40ede55
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a3e2f22e-d4a1-4050-a8a8-5a2588565002 # Disable Ads
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6190f9f-4cb4-497f-9873-dddeeedf433f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 9f8b1321-32e1-43c3-8fd3-5bb348d7da6f
            userCondition: null
          -
            elementCondition: null
            fieldUid: ed962f96-407c-48ee-9fe2-daccbb4b7a16 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: 'CTA Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d742b8bb-19a8-4ee2-b3be-b332bf29745a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 68c36b78-e56c-45f0-90a2-b93ccc0f1ee6 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e058431-ea2b-4822-a87b-09952466593b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 67f925c7-9b91-4a95-b700-1b99ee38057f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac112358-b098-4b74-b9fe-763ece5d27e0 # Meta Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d670be16-05fa-4a27-9168-5e34585afb6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e55684f7-379f-42d4-8c46-0d4bca63ecee # Meta Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7852defc-9888-452e-8535-4d7f4d7570b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a780297-6f26-445e-ab9a-59602ffc5dbc # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d31e5458-1229-4a16-ab66-1e0f3fb952f6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e7651b06-b1bb-453f-857b-e90fb27deca7
        userCondition: null
handle: homepage
hasTitleField: false
icon: ''
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: ''
titleTranslationMethod: site
