color: orange
fieldLayouts:
  0b1cf13f-23a0-4104-9ec8-e18046ded0e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c39066dc-350a-44ca-b7b7-625659cbf4a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0e0a64-f0b3-42c2-b38a-3bd34bf15cb4 # Blog Content - Image & Text - Headline
            handle: headline
            includeInCards: true
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22816e1a-471e-417c-ab9a-11e76cf016eb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9ea32fa5-e1b5-4900-96a6-86c01b8dbc68 # Blog Content - Image & Text - Subheadline
            handle: subheadline
            includeInCards: false
            instructions: null
            label: Subheadline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c91b1eff-0402-4c5e-b70e-19dc09231e04
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7517c439-55f4-420f-9514-cad4d205f293 # Blog Content - Image & Text - Alternate TOC Text
            handle: alternateTocText
            includeInCards: false
            instructions: null
            label: 'Alternate TOC Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef2dc748-c9ab-45b5-83db-7aca2065b9d2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 13766b7f-d24e-46e5-9254-0013aad2f574
            userCondition: null
          -
            elementCondition: null
            fieldUid: 602a04aa-8d14-4db6-93a0-9c9f79d8d72d # Ranker Value
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a16692d1-3f1f-4a62-81b0-d2948040feec
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3d8afd6b-d100-47e2-a8fe-0be9e0dab4d4 # Ranker Key
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e4f230-9a6f-4f4c-b6a0-9f36aefb687d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 156268e6-7910-431e-b8d6-19255da5977f
            userCondition: null
          -
            elementCondition: null
            fieldUid: 9b6b4041-451d-480f-bfb4-9116294162ad # Blog Content - Image & Text - Blog Image
            handle: blogImage
            includeInCards: false
            instructions: null
            label: 'Blog Image'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92b9746a-6b5a-46f4-bdcd-04de975429f8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d30b8ce1-04a4-4e95-a1e6-570d2e4f339f # Blog Content - Image & Text - No Transform
            handle: noTransform
            includeInCards: false
            instructions: null
            label: 'No Transform'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fa32bdb-5405-4be9-8434-6e142132ebf9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6c48f2a4-30de-4d42-a211-268e766bd9b1 # Blog Content - Image & Text - Size
            handle: size
            includeInCards: false
            instructions: null
            label: Size
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88f4edb1-f1d9-46d2-b639-48ac6761d4db
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 055b60fb-8617-44d9-aa31-c628008126b0 # Blog Content - Image & Text - Caption
            handle: caption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 742a1a3e-4d71-45d6-a10c-de161b1dc1f2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7753be54-298e-490f-9ab3-381c71785210 # Blog Content - Image & Text - Link URL
            handle: linkUrl
            includeInCards: false
            instructions: null
            label: 'Link URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f89fc82-4995-46ba-a633-1f527e6c9041
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 1a8e5526-c428-4e27-8f92-b916aabfb439
            userCondition: null
          -
            elementCondition: null
            fieldUid: 555e19eb-df0c-48bc-b4b9-bdc423af2204 # Blog Content - Image & Text - Rich Text
            handle: richText
            includeInCards: false
            instructions: null
            label: 'Rich Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe2ceaa0-6184-4f90-9ac0-8bcb2292989b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d49894c-7b89-485b-a00d-c6782a84e522
        userCondition: null
handle: imageText
hasTitleField: false
icon: text
name: 'Image & Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
