color: orange
fieldLayouts:
  6c07c85b-3229-42fe-a6df-9b905ad7c243:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: feea1186-954c-4093-80e3-e87af0caa9de
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 2d08e6f3-ae71-4a17-a1f5-97abeb7193f9 # Blog Content - Image - Blog Image
            handle: blogImage
            includeInCards: false
            instructions: null
            label: 'Blog Image'
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9aaf9382-7cfe-4e14-baf5-0b5ff5f5e202
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: d99087f8-d76e-43c8-86f5-afc78b3f4430 # Blog Content - Image - No Transform
            handle: null
            includeInCards: true
            instructions: null
            label: 'No Transform'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aadab461-22e3-4473-a681-ab14e0fe878e
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: e0270692-1ca3-4ba6-8d52-cfca54ac634a # Blog Content - Image - Size
            handle: null
            includeInCards: false
            instructions: null
            label: Size
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8abe46ae-628c-4f71-9268-d707f5ab4d34
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: a070ee30-4cf4-4a25-8bb8-7768d85f66f7 # Blog Content - Image - Background
            handle: null
            includeInCards: false
            instructions: null
            label: Background
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23dbf577-fd5c-4616-a91c-a2fb07aa4cf6
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 82e0e8c4-4d0e-4fc4-83f5-1a60298d9dcc # Blog Content - Image - Margins
            handle: null
            includeInCards: false
            instructions: null
            label: Margins
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b9889d7-1bb4-41a8-9ca4-25beccda29f5
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1c1054c9-4810-4918-b3c1-3bd0d6a13675 # Blog Content - Image - Caption
            handle: null
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 935b4c4a-7762-4cc5-b83a-2a004805395f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 26e93876-a78a-402d-b49e-a55f7d4e5374 # Blog Content - Image - Link URL
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 463a190e-9b2b-46c6-8afc-6cf3c4477d65
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 763c3c27-d89d-4fc6-ac15-ab0e8b3fbd37
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
