color: null
fieldLayouts:
  32ff5fa9-ae86-43ff-a044-23279a1bb95f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cfb09c71-886c-4dfa-b6b6-64d4db15a4ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee13e705-afd8-41c1-a111-b472a62a15f2 # Blog Content - Section Title - Headline
            handle: headline
            includeInCards: true
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc4157cf-46ba-43de-8c9b-a98188566f38
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: acdcd6cb-c200-42d3-a723-ea131a1387dd # Blog Content - Section Title - Subheadline
            handle: subheadline
            includeInCards: false
            instructions: null
            label: Subheadline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41349afd-2468-4919-bf14-364f7ef8932a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e47520eb-bf67-40c5-b8e9-b5e219b14003 # Blog Content - Section Title - Alternate TOC Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Alternate TOC Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a70245f7-003a-4ce1-937c-1ecba1aaa24a
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 6c4d8031-9950-49c3-9f52-6a52a2cdfb94
        userCondition: null
handle: sectionTitle
hasTitleField: false
icon: null
name: 'Section Title'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
