color: null
fieldLayouts:
  4f4ed56c-1fee-4168-801f-70ad11dbe0d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ee22ab3c-e5d3-44b1-915f-1c9fb04859ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68c36b78-e56c-45f0-90a2-b93ccc0f1ee6 # Blog Content - Text - Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Rich Text'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9a10396-11e9-4c6f-b28b-bc60e30a3000
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ab7943e-e0be-449b-af79-0c80d3182846
        userCondition: null
handle: text
hasTitleField: false
icon: ''
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
