color: orange
fieldLayouts:
  c91726f1-251a-45ca-90c8-c064110379c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'Converted to a slug as the Ranker Key'
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6cd42f77-3790-4e03-b117-55cf32b5d9dc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7338fd63-9ce2-4696-a9b3-113b5d6015c3 # Subheadline
            handle: null
            includeInCards: false
            instructions: 'Optional title under headline'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c425c16b-9f2b-4647-84c9-6cd2a37624d3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 68c36b78-e56c-45f0-90a2-b93ccc0f1ee6 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc181dc2-53ce-4542-945e-b42948808c39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80a9c5e0-fb80-420c-a7df-676f56ac600d # Blog Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a8f18dc-eb7f-4ccd-a132-da570d6960ae
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: aae926e2-c2e8-4a90-8787-fa6597dacd90 # Header Tag
            handle: null
            includeInCards: false
            instructions: null
            label: 'Header Tag'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7ffb1ea-3984-4052-aceb-39d3e6925070
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e1e2658d-253a-4426-b447-fce24b18410a # Website URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecb9bc8c-de53-4625-842a-21017b8475c2
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: befa7b3c-0af1-4895-83ef-126ba821480e
        userCondition: null
handle: thumbnailRow
hasTitleField: true
icon: list-timeline
name: 'Thumbnail Row'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
