color: null
fieldLayouts:
  705149bd-e05b-41c7-94b8-f3e0253ba2c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a5f8367-c8cf-4a93-ad10-1e3d96f2656c
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: a3e2f22e-d4a1-4050-a8a8-5a2588565002 # Disable Ads
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8278a32b-7085-40cc-86c8-07004e4570e0
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ed962f96-407c-48ee-9fe2-daccbb4b7a16 # Headline
            handle: null
            includeInCards: false
            instructions: 'H1 Tag (Menu Items Use Title)'
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a879e4b-10da-4528-b595-0d878c19bc75
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 02fb6a1a-8498-4b48-ad99-b61ac895f168 # CTA Text
            handle: null
            includeInCards: false
            instructions: 'Text used in the tag icon'
            label: Label
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ba8e49f-7197-4ea8-a0ca-1a3baed9ec5f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1b12d4c8-a449-4b45-99db-cdcf801d8fa4 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ef4719b-4b8e-43d7-bc48-6e658ab6d1f0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 6025339c-6b5a-4573-bfec-83f93d0f041a # Percent
            handle: null
            includeInCards: false
            instructions: null
            label: 'Header Brightness'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d415abd-8a4e-41fa-ba5d-2288620503e9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 7338fd63-9ce2-4696-a9b3-113b5d6015c3 # Subheadline
            handle: null
            includeInCards: false
            instructions: null
            label: 'Description Headline'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86754af7-22dc-4f00-b905-270259ed8f6c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 9d9d41d0-9e17-402e-8e87-a5d4346dce47 # Short Description
            handle: null
            includeInCards: false
            instructions: null
            label: 'Description Text'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd3ffccd-443f-4e1c-9029-3e1d9d6594c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 8bb43633-4a68-4f44-93b1-84ef2584a366 # CTA Text 2
            handle: null
            includeInCards: false
            instructions: null
            label: 'Search Placeholder'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2ecbb78-7b15-44b8-8aec-8dab4305d2e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 82e52c13-cbb5-435e-936b-296b40cf8f27 # Featured Blog Post
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d634987c-1593-4b0d-be6e-0e71c6cdcbf7
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 2075787e-20ab-458f-81df-dd47b726a51b # Show
            handle: null
            includeInCards: false
            instructions: null
            label: 'Show In Menu'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d684a2d0-5d7c-4a8e-b6ce-7bfcee2d6d30
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 8738dbd4-2302-4215-b0a0-84158c48a9ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ac112358-b098-4b74-b9fe-763ece5d27e0 # Meta Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfada920-16a5-43d4-87dc-040076e2d362
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: e55684f7-379f-42d4-8c46-0d4bca63ecee # Meta Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93844c9a-959d-41dd-9ecb-aeb20ef3e4e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 8a780297-6f26-445e-ab9a-59602ffc5dbc # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ddff141-8497-4f42-a8bc-5866976e847f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 0f138e01-eddc-4fef-b078-5f2fa151e0e7
        userCondition: null
handle: topics_default
hasTitleField: true
icon: null
name: 'Topics - Default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
