headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Default
options:
  alignment:
    options:
      - left
      - center
      - right
  htmlSupport:
    allow:
      -
        attributes: true
        classes: true
        styles: true
  style:
    definitions:
      -
        classes:
          - btn
        element: a
        name: Button
toolbar:
  - heading
  - style
  - bold
  - italic
  - underline
  - strikethrough
  - link
  - bulletedList
  - numberedList
  - alignment
  - sourceEditing
