headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Default
options:
  alignment:
    options:
      - left
      - right
toolbar:
  - heading
  - bold
  - italic
  - underline
  - strikethrough
  - link
  - bulletedList
  - numberedList
  - alignment
  - sourceEditing
