headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Default
options:
  alignment:
    options:
      - left
      - center
      - justify
      - right
  htmlSupport:
    allow:
      -
        attributes: true
        classes: true
        styles: true
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - heading
  - style
  - bold
  - italic
  - underline
  - strikethrough
  - link
  - bulletedList
  - numberedList
  - alignment
  - sourceEditing
