headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  htmlSupport:
    allow:
      -
        attributes: true
        classes: true
        styles: true
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - sourceEditing
