altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  97647aaa-7576-4b16-ae25-8b8a2857448c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7d324fe9-cc85-41e7-b9d1-bbc34991db6b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 55b24a12-bbe3-4b4e-8bfe-4df077efbf1a
        userCondition: null
fs: bandImages
handle: bandImages
name: 'Band Images'
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
