altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9335533e-fabd-459e-bdaf-5afd6c779c19:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bb914046-a2e9-4490-81a3-d7f5ffc67cc1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 511ac5f8-99f5-48c0-afd9-7fa7bfa2a568
        userCondition: null
fs: blogImages
handle: blogImages
name: 'Blog Images'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
