columnSuffix: sejwfnam
contentColumnType: string(8)
handle: contentLayout
instructions: null
name: 'Content Layout'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - 'Rich Text'
        -
          - value
          - richText
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Z Pattern'
        -
          - value
          - zPattern
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
