columnSuffix: ctfamrlw
contentColumnType: text
handle: ctaText2
instructions: null
name: 'CTA Text 2'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
