columnSuffix: nyqrnzwp
contentColumnType: boolean
handle: disableAds
instructions: null
name: 'Disable Ads'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
