columnSuffix: diserads
contentColumnType: boolean
fieldGroup: a9c9ed2d-71ed-44ae-8360-214ea6ecda29 # SEO Keywords
handle: dynamicSeo
instructions: null
name: 'Dynamic SEO'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
