columnSuffix: null
handle: enableRanking
instructions: null
name: 'Enable Ranking'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
