columnSuffix: null
contentColumnType: string
handle: featuredBlogPost
instructions: 'If not entered the most recent article will be highlighted on the homepage.'
name: 'Featured Blog Post'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:ed3ddcd0-5218-490f-a4b7-d5000594dcf2' # Blog Post
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
