columnSuffix: qnjolmmo
handle: figureType
instructions: null
name: 'Blog Content - Embed Code - Figure Type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - TikTok
        -
          - value
          - tiktok
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
