columnSuffix: ohacztqp
contentColumnType: boolean
handle: indexed
instructions: null
name: Ranking
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
