columnSuffix: mlehtxum
handle: linkUrl2
instructions: null
name: 'Blog Content - Image & Text - Link URL'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
