columnSuffix: kfgqnhgm
handle: longText2
instructions: null
name: 'Long Text 2'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: cc64f857-3e97-42d7-8a16-79223c695a98 # Default
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
