columnSuffix: kfgqnhgm
contentColumnType: text
fieldGroup: fa511e02-7c6f-4081-9701-b14c76ecf31a # Common
handle: longText2
instructions: null
name: 'Long Text 2'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: cc64f857-3e97-42d7-8a16-79223c695a98 # Default
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
