columnSuffix: vwjuhafb
contentColumnType: text
handle: longDescription
instructions: null
name: 'Long Description'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: cc64f857-3e97-42d7-8a16-79223c695a98 # Default
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
