columnSuffix: trmcykfn
handle: markup
instructions: null
name: 'Blog Content - Embed Code - Markup'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
