columnSuffix: mgglwxhu
handle: mediaType
instructions: null
name: 'Blog Content - Media - Media Type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Instagram
        -
          - value
          - instagram
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
