columnSuffix: lelbwxkj
contentColumnType: string(256)
fieldGroup: fa511e02-7c6f-4081-9701-b14c76ecf31a # Common
handle: metaTitle
instructions: null
name: 'Meta Title'
searchable: true
settings:
  byteLimit: null
  charLimit: 64
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
