columnSuffix: xlyfqclg
handle: minuteMark
instructions: null
name: 'Blog Content - Media - Minute Mark'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'in seconds (i.e. "264" for 4:24)'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
