columnSuffix: zmtpeewv
handle: noTransform
instructions: null
name: 'Blog Content - Image - No Transform'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
