columnSuffix: idtehzok
handle: opacity
instructions: null
name: Opacity
searchable: false
settings:
  decimals: 2
  defaultValue: 0.35
  max: 1
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
