columnSuffix: null
handle: plainText
instructions: null
name: 'Header Tag'
searchable: false
settings:
  byteLimit: null
  charLimit: 2
  code: false
  initialRows: 4
  multiline: false
  placeholder: h2
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
