columnSuffix: null
handle: rankOptions
instructions: null
name: 'Ranking Options'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'All Options'
        -
          - value
          - allOptions
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Like Buttons Only'
        -
          - value
          - likeButtonsOnly
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
