columnSuffix: null
handle: rankButtonLocation
instructions: null
name: 'Rank Button Location'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default Location'
        -
          - value
          - default-location
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Absolute Right'
        -
          - value
          - rank-buttons-right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
