columnSuffix: null
handle: rankerValue
instructions: 'Will use the displayed headline or subheadline if empty'
name: 'Ranker Value'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
