columnSuffix: null
handle: reverse
instructions: null
name: Reverse
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
