columnSuffix: pdgqabpk
contentColumnType: string
handle: seoKeywords
instructions: null
name: 'Related SEO Keywords'
searchable: false
translationKeyFormat: null
translationMethod: none
type: bandpioneer\rockstar\fields\SeoKeywords
