columnSuffix: mmlrtbal
handle: show
instructions: null
name: Show
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
