columnSuffix: mskyifeo
handle: showImageCarousel
instructions: null
name: 'Show Image Carousel'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
