columnSuffix: ndhscpec
handle: subheadline2
instructions: null
name: 'Blog Content - Section Title - Subheadline'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
