columnSuffix: rhcnsoll
contentColumnType: text
handle: subheadline
instructions: null
name: Subheadline
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
