columnSuffix: null
contentColumnType: string
fieldGroup: fa511e02-7c6f-4081-9701-b14c76ecf31a # Common
handle: topic
instructions: null
name: Topic
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 2
  minRelations: 1
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:04623371-fa0e-4ff7-84f9-93dcf4e31080' # Topics
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
