columnSuffix: ysesehfe
handle: websiteUrl
instructions: null
name: 'Website URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
