dateModified: 1670544343
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - link
      type: native
    -
      heading: Blog
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:ed3ddcd0-5218-490f-a4b7-d5000594dcf2' # Blog Post
      tableAttributes:
        - 'field:a47603f2-0b4e-42c5-9f37-84cc7ceac8f0' # Categories
        - 'field:80a9c5e0-fb80-420c-a7df-676f56ac600d' # Blog Image
        - dateUpdated
        - postDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:04623371-fa0e-4ff7-84f9-93dcf4e31080' # Category
      tableAttributes:
        - 'field:9d9d41d0-9e17-402e-8e87-a5d4346dce47' # Short Description
        - 'field:2075787e-20ab-458f-81df-dd47b726a51b' # Show
        - slug
        - dateUpdated
        - link
      type: native
email:
  fromEmail: jack@realitygems.com
  fromName: 'Band Pioneer'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  blogImages:
    hasUrls: true
    name: 'Blog Images'
    settings:
      path: assets/images/blog
    type: craft\fs\Local
    url: /assets/images/blog
  writerPictures:
    hasUrls: true
    name: 'Writer Pictures'
    settings:
      path: assets/images/writers
    type: craft\fs\Local
    url: /assets/images/writers
meta:
  __names__:
    1a69adf3-7129-4f03-a788-c50df99aa120: 'Band Pioneer' # Band Pioneer
    1c1054c9-4810-4918-b3c1-3bd0d6a13675: Caption # Caption
    2d08e6f3-ae71-4a17-a1f5-97abeb7193f9: 'Blog Image' # Blog Image
    5eff53ba-9583-4e3e-92ce-d1d630f3f363: 'YouTube ID' # YouTube ID
    7f387f1a-d0e5-455a-a900-c8632cfdf5c9: Text # Text
    9d9d41d0-9e17-402e-8e87-a5d4346dce47: 'Short Description' # Short Description
    18b5ed4a-3fe4-4566-8c78-9cff10344f5b: 'Section Title' # Section Title
    21c3bed7-573e-4590-a1f1-9255d64cd4d0: 'Website Name' # Website Name
    26e93876-a78a-402d-b49e-a55f7d4e5374: 'Link URL' # Link URL
    30fa7a57-b433-476a-9e42-ca0ad4755591: Image # Image
    61ce33f4-2d2f-429c-89f0-3011ff78cd5f: Homepage # Homepage
    067eba0e-b12d-4661-a61b-9c4a22c91bb4: Video # Video
    68c36b78-e56c-45f0-90a2-b93ccc0f1ee6: 'Rich Text' # Rich Text
    76f42882-6b79-4288-b04b-76c67c5e6781: 'Writer Picture' # Writer Picture
    80a9c5e0-fb80-420c-a7df-676f56ac600d: 'Blog Image' # Blog Image
    780b6c3d-696e-4d13-8ec9-85dc01bce659: 'Featured Post' # Featured Post
    6783d966-6cc3-4df4-afa4-e9790815a363: 'Long Description' # Long Description
    24792e71-a84c-4970-acf7-c69480e02e11: 'Writer Picture' # Writer Picture
    266355e1-d1f3-4d71-a92d-2d3a714c3d06: 'Blog Content' # Blog Content
    2075787e-20ab-458f-81df-dd47b726a51b: Show # Show
    04623371-fa0e-4ff7-84f9-93dcf4e31080: Category # Category
    33001227-43a9-4c08-8a5c-5e8bf0e4e3ac: Markup # Markup
    a05d873a-0743-4aa3-8da6-214e223452fa: 'Blog Post' # Blog Post
    a47603f2-0b4e-42c5-9f37-84cc7ceac8f0: Categories # Categories
    acdcd6cb-c200-42d3-a723-ea131a1387dd: Subheadline # Subheadline
    c974eade-af8a-4f73-a577-d015bbb0f5f4: 'Related Post' # Related Post
    c1052de8-6217-41e9-8c24-2b4da3d48b10: 'Blog Images' # Blog Images
    cb12ca30-b685-4547-a81e-f978eb629278: Default # Default
    d868a59a-8531-43b1-88a2-eb8eea29254c: 'Band Pioneer' # Band Pioneer
    dc2a5508-39c8-4963-bf3b-159da3ef325b: Default # Default
    de2bb280-3465-478f-a8b2-bb03f3c7be35: Caption # Caption
    e1e2658d-253a-4426-b447-fce24b18410a: 'Website URL' # Website URL
    eb6cec15-707d-4542-8311-cb925d61ee30: Homepage # Homepage
    ed3ddcd0-5218-490f-a4b7-d5000594dcf2: 'Blog Post' # Blog Post
    ee13e705-afd8-41c1-a111-b472a62a15f2: Headline # Headline
    f0b910e3-c8e6-448c-b884-50e6ab61d4da: 'Writer Pictures' # Writer Pictures
    f56dcf7f-956d-4a14-b4e8-8bfd842d5b72: 'Embed Code' # Embed Code
    f85c3fd3-04eb-4069-a712-f8725e5c5fac: 'Full Name' # Full Name
    f663d014-30ef-4783-b5bd-8c974833fe36: Opacity # Opacity
    fa511e02-7c6f-4081-9701-b14c76ecf31a: Common # Common
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Band Pioneer'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
