dateModified: 1681236014
elementSources:
  craft\elements\Asset:
    -
      key: 'folder:4f837d0a-f4ae-450a-b862-c89db9245dd0'
      type: native
    -
      heading: Website
      type: heading
    -
      key: 'volume:3098d7ae-88a8-4d10-9c0f-b138a839a277' # Band Images
      type: native
    -
      key: 'volume:c1052de8-6217-41e9-8c24-2b4da3d48b10' # Blog Images
      type: native
    -
      key: 'volume:3da0f593-6bb6-42b6-834b-85a544cbc005' # Page Images
      type: native
    -
      key: 'volume:f0b910e3-c8e6-448c-b884-50e6ab61d4da' # Writer Pictures
      type: native
    -
      heading: Rockstars
      type: heading
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:eedcf843-b27f-4c8b-a016-8ed1d7bbbd43' # Rockstars Assets
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: 'Web Pages'
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:73181943-f37b-46c9-bd22-4f9c35a4af07' # Pages
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      heading: Blog
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:ed3ddcd0-5218-490f-a4b7-d5000594dcf2' # Blog Post
      tableAttributes:
        - 'field:7338fd63-9ce2-4696-a9b3-113b5d6015c3' # Subheadline
        - type
        - 'field:a47603f2-0b4e-42c5-9f37-84cc7ceac8f0' # Category
        - 'field:f85c3fd3-04eb-4069-a712-f8725e5c5fac' # Full Name
        - postDate
        - 'field:9fb102dd-839a-4229-82ce-229ed6669f92' # Indexed
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:04623371-fa0e-4ff7-84f9-93dcf4e31080' # Category
      tableAttributes:
        - 'field:ed962f96-407c-48ee-9fe2-daccbb4b7a16' # Headline
        - 'field:9d9d41d0-9e17-402e-8e87-a5d4346dce47' # Short Description
        - 'field:2075787e-20ab-458f-81df-dd47b726a51b' # Show
        - slug
        - dateUpdated
        - link
      type: native
    -
      heading: Components
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:2ee0929d-42ad-44ca-9f6a-990c73c36c1c' # Bands
      tableAttributes:
        - 'field:37ff1ae6-ced2-4eaf-b107-93e6e3dd94be' # Band Image
        - dateUpdated
      type: native
    -
      heading: Rockstars
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:aa743bfb-7d05-4d44-943b-7bf893d5cbd3' # Genres
      tableAttributes: '-'
      type: native
email:
  fromEmail: support@realitygems.com
  fromName: 'Band Pioneer'
  replyToEmail: support@realitygems.com
  template: ''
  transportSettings:
    apiKey: $SENDGRID_API_KEY
    categories: ''
  transportType: putyourlightson\sendgrid\mail\SendgridAdapter
fs:
  bandImages:
    hasUrls: true
    name: 'Band Images'
    settings:
      path: assets/images/bands
    type: craft\fs\Local
    url: /assets/images/bands
  blogImages:
    hasUrls: true
    name: 'Blog Images'
    settings:
      path: assets/images/blog
    type: craft\fs\Local
    url: /assets/images/blog
  pageImages:
    hasUrls: true
    name: 'Page Images'
    settings:
      path: assets/images/pages
    type: craft\fs\Local
    url: /assets/images/pages
  rockstarFiles:
    hasUrls: true
    name: 'Rockstar Files'
    settings:
      path: assets/rockstars
    type: craft\fs\Local
    url: /assets/rockstars
  writerPictures:
    hasUrls: true
    name: 'Writer Pictures'
    settings:
      path: assets/images/writers
    type: craft\fs\Local
    url: /assets/images/writers
meta:
  __names__:
    00db73da-9688-48d8-b88d-cf5fc233f346: 'Show Image Carousel' # Show Image Carousel
    1a69adf3-7129-4f03-a788-c50df99aa120: 'Band Pioneer' # Band Pioneer
    1b12d4c8-a449-4b45-99db-cdcf801d8fa4: 'Hero Image' # Hero Image
    1c1054c9-4810-4918-b3c1-3bd0d6a13675: Caption # Caption
    1e42cdc3-f360-43ac-b612-8de6f081ad47: Rockstars # Rockstars
    2d08e6f3-ae71-4a17-a1f5-97abeb7193f9: 'Blog Image' # Blog Image
    2ee0929d-42ad-44ca-9f6a-990c73c36c1c: Bands # Bands
    02fb6a1a-8498-4b48-ad99-b61ac895f168: 'CTA Text' # CTA Text
    3a004cc4-6ba5-45b9-8767-56d39280f6f8: 'Twitter Image' # Twitter Image
    3da0f593-6bb6-42b6-834b-85a544cbc005: 'Page Images' # Page Images
    5eff53ba-9583-4e3e-92ce-d1d630f3f363: 'YouTube ID' # YouTube ID
    6bbbdbbd-d9a0-42e4-acd4-7295e2f1644e: External # External
    7a24ff15-e5fa-431b-870a-78cdc208ee76: 'Long Text 2' # Long Text 2
    7f387f1a-d0e5-455a-a900-c8632cfdf5c9: Text # Text
    8a780297-6f26-445e-ab9a-59602ffc5dbc: 'SEO Image' # SEO Image
    8c0e4ec9-bf67-46e2-9302-82d3a602160c: Default # Default
    9a6940a2-21f7-479b-89de-7b12ff94ad18: 'Long Text' # Long Text
    09c9f08d-1475-4099-81fb-50a41a1eca8e: 'Blog Image' # Blog Image
    9d9d41d0-9e17-402e-8e87-a5d4346dce47: 'Short Description' # Short Description
    9fb102dd-839a-4229-82ce-229ed6669f92: Indexed # Indexed
    16f6ab19-b9a9-4d9d-bef0-1b25bf8877ef: 'Blog Header' # Blog Header
    18b5ed4a-3fe4-4566-8c78-9cff10344f5b: 'Section Title' # Section Title
    21c3bed7-573e-4590-a1f1-9255d64cd4d0: 'Website Name' # Website Name
    26e93876-a78a-402d-b49e-a55f7d4e5374: 'Link URL' # Link URL
    30fa7a57-b433-476a-9e42-ca0ad4755591: Image # Image
    37ff1ae6-ced2-4eaf-b107-93e6e3dd94be: 'Band Image' # Band Image
    61ce33f4-2d2f-429c-89f0-3011ff78cd5f: Homepage # Homepage
    067eba0e-b12d-4661-a61b-9c4a22c91bb4: Video # Video
    68c36b78-e56c-45f0-90a2-b93ccc0f1ee6: 'Rich Text' # Rich Text
    69a773a9-c69f-4fe7-b975-b60c93c084a7: 'Show Recent Blogs' # Show Recent Blogs
    76f42882-6b79-4288-b04b-76c67c5e6781: 'Writer Picture' # Writer Picture
    80a9c5e0-fb80-420c-a7df-676f56ac600d: 'Blog Image' # Blog Image
    82e0e8c4-4d0e-4fc4-83f5-1a60298d9dcc: Margins # Margins
    260aeb04-6305-4b90-8f63-8cb1ab20e042: 'Single Line Text' # Single Line Text
    780b6c3d-696e-4d13-8ec9-85dc01bce659: 'Featured Post' # Featured Post
    2297cf40-712c-48f0-9804-74a835b2f5f6: Default # Default
    3098d7ae-88a8-4d10-9c0f-b138a839a277: 'Band Images' # Band Images
    6783d966-6cc3-4df4-afa4-e9790815a363: 'Long Description' # Long Description
    7149d8a6-d74b-4e10-b59b-80f37708aaa0: 'TOC Style' # TOC Style
    7338fd63-9ce2-4696-a9b3-113b5d6015c3: Subheadline # Subheadline
    7713ee4e-e1ca-4aeb-a2c4-ef6b725b1a18: 'Page Image' # Page Image
    24792e71-a84c-4970-acf7-c69480e02e11: 'Writer Picture' # Writer Picture
    266355e1-d1f3-4d71-a92d-2d3a714c3d06: 'Blog Content' # Blog Content
    2075787e-20ab-458f-81df-dd47b726a51b: Show # Show
    04623371-fa0e-4ff7-84f9-93dcf4e31080: Category # Category
    6025339c-6b5a-4573-bfec-83f93d0f041a: Percent # Percent
    33001227-43a9-4c08-8a5c-5e8bf0e4e3ac: Markup # Markup
    73181943-f37b-46c9-bd22-4f9c35a4af07: Pages # Pages
    a05d873a-0743-4aa3-8da6-214e223452fa: 'Blog Post' # Blog Post
    a7a58192-5546-4595-bb65-35dc012b65cc: 'Band Carousel' # Band Carousel
    a8e7e839-8b79-4e99-a8e2-a2ba56f6e057: 'OG Image' # OG Image
    a47603f2-0b4e-42c5-9f37-84cc7ceac8f0: Category # Category
    aa743bfb-7d05-4d44-943b-7bf893d5cbd3: Genres # Genres
    ac112358-b098-4b74-b9fe-763ece5d27e0: 'Meta Title' # Meta Title
    acdcd6cb-c200-42d3-a723-ea131a1387dd: Subheadline # Subheadline
    b7ec030d-fd66-4c86-be9c-5cec826a7638: Change # Change
    c974eade-af8a-4f73-a577-d015bbb0f5f4: 'Related Post' # Related Post
    c1052de8-6217-41e9-8c24-2b4da3d48b10: 'Blog Images' # Blog Images
    cb12ca30-b685-4547-a81e-f978eb629278: Internal # Internal
    d868a59a-8531-43b1-88a2-eb8eea29254c: 'Band Pioneer' # Band Pioneer
    d99087f8-d76e-43c8-86f5-afc78b3f4430: 'No Transform' # No Transform
    dc2a5508-39c8-4963-bf3b-159da3ef325b: Default # Default
    de2bb280-3465-478f-a8b2-bb03f3c7be35: Caption # Caption
    e0270692-1ca3-4ba6-8d52-cfca54ac634a: Size # Size
    e1e2658d-253a-4426-b447-fce24b18410a: 'Website URL' # Website URL
    e8ce77e6-c957-4290-8a2d-87ba28953701: 'Bands Media' # Bands Media
    e55684f7-379f-42d4-8c46-0d4bca63ecee: 'Meta Description' # Meta Description
    eb6cec15-707d-4542-8311-cb925d61ee30: Homepage # Homepage
    ed3ddcd0-5218-490f-a4b7-d5000594dcf2: 'Blog Post' # Blog Post
    ed962f96-407c-48ee-9fe2-daccbb4b7a16: Headline # Headline
    ee13e705-afd8-41c1-a111-b472a62a15f2: Headline # Headline
    eedcf843-b27f-4c8b-a016-8ed1d7bbbd43: 'Rockstars Assets' # Rockstars Assets
    f0b910e3-c8e6-448c-b884-50e6ab61d4da: 'Writer Pictures' # Writer Pictures
    f56dcf7f-956d-4a14-b4e8-8bfd842d5b72: 'Embed Code' # Embed Code
    f85c3fd3-04eb-4069-a712-f8725e5c5fac: 'Full Name' # Full Name
    f663d014-30ef-4783-b5bd-8c974833fe36: Opacity # Opacity
    fa511e02-7c6f-4081-9701-b14c76ecf31a: Common # Common
    fab3405a-11f1-4389-b8fb-d7f3fae15087: 'Featured Snippet' # Featured Snippet
    fd86eaf9-b505-4c30-8bd9-37be31ad6209: Default # Default
plugins:
  comments:
    edition: standard
    enabled: true
    licenseKey: BBH82OI6SFY4ZXR0TIXEYSUT
    schemaVersion: 1.1.7
    settings:
      allowFlagging: true
      allowGuest: true
      allowGuestFlagging: false
      allowGuestVoting: false
      allowVoting: false
      autoCloseDays: null
      closed: false
      defaultQueryStatus:
        - approved
      downvoteCommentLimit: 5
      enableGravatar: false
      enableSpamChecks: true
      flaggedCommentLimit: 5
      guestNotice: null
      guestRequireEmailName: true
      guestShowEmailName: false
      hideVotingForThreshold: false
      indexSidebarGroup: true
      indexSidebarIndividualElements: false
      indexSidebarLimit: 25
      maxReplyDepth: null
      maxUserComments: null
      moderatorUserGroup: null
      notificationAdminEnabled: false
      notificationAuthorEnabled: true
      notificationFlaggedEnabled: false
      notificationModeratorApprovedEnabled: false
      notificationModeratorEnabled: false
      notificationReplyEnabled: true
      notificationSubscribeAuto: false
      notificationSubscribeCommentEnabled: false
      notificationSubscribeDefault: true
      notificationSubscribeEnabled: false
      outputDefaultCss: true
      outputDefaultJs: true
      permissions:
        __assoc__:
          -
            - craft\elements\Asset
            - '*'
          -
            - craft\elements\Category
            - '*'
          -
            - craft\elements\Entry
            - '*'
          -
            - craft\elements\User
            - '*'
      placeholderAvatar: null
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      requireModeration: true
      securityBanned: null
      securityFlooding: null
      securityMatchExact: false
      securityMaxLength: null
      securityModeration: null
      securitySpamlist: null
      showAvatar: true
      showCustomFieldInstructions: false
      showCustomFieldNames: false
      showTimeAgo: true
      sortDefaultDirection: asc
      sortDefaultKey: structure
      structureUid: 4cf07fcd-fffb-4883-8066-1202ee8c9ea8
      templateEmail: null
      templateFolderOverride: _comments
      useQueueForNotifications: false
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields:
        - Phone
      prependSender: 'Band Pioneer'
      prependSubject: 'Band Pioneer'
      successFlashMessage: 'Thank you! Your message has been sent.'
      toEmail: jack@bandpioneer.com
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  rockstar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sendgrid:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Band Pioneer'
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: America/New_York
