fieldLayouts:
  6bd49627-963e-41b4-9514-220f72bdeaa7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 82e52c13-cbb5-435e-936b-296b40cf8f27 # Featured Blog Post
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a58f0594-ea4a-448c-ac01-2c8c67446736
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d894e72-ea22-4785-8c26-c43a3b823625 # Popular Posts
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9357b8a3-30d5-4651-aef4-ac5600b1cdd0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77bee9c6-a3ce-4ca6-ae83-75613901a67e # Default Blog Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06953258-ff0d-44f1-9572-1118680fa272
            userCondition: null
            warning: null
            width: 100
        name: Blog
        uid: 3b2fe010-0f9d-4b22-98ac-206bb45c578c
        userCondition: null
handle: blog
name: Blog
sortOrder: 1
