defaultPlacement: end
enableVersioning: true
entryTypes:
  - cb12ca30-b685-4547-a81e-f978eb629278 # Blog - Internal
  - 6bbbdbbd-d9a0-42e4-acd4-7295e2f1644e # Blog - External
  - 350ca85e-fc53-44c8-a062-e0256f1967e4 # Blog - Dynamic
handle: blog
maxAuthors: 1
name: 'Blog Post'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Blog Post Preview'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1a69adf3-7129-4f03-a788-c50df99aa120: # Band Pioneer
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: '{% if object.type != ''external'' %}{object.topic.one().slug}/{slug}{% endif %}'
type: channel
