defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8c0e4ec9-bf67-46e2-9302-82d3a602160c # Genre
  - 774ccc9c-38af-4883-8507-dc63a256627a # Instrument
  - d70ad590-bed7-4878-a8d8-ca2759e4ae4d # Decade
handle: categories
maxAuthors: 1
name: Categories
propagationMethod: all
siteSettings:
  1a69adf3-7129-4f03-a788-c50df99aa120: # Band Pioneer
    enabledByDefault: true
    hasUrls: true
    template: blog/_index
    uriFormat: '{% if object.show %}{object.type.handle}/{slug}{% endif %}'
structure:
  maxLevels: 1
  uid: f368757a-011d-4876-80ee-329cca15484e
type: structure
