defaultPlacement: end
enableVersioning: true
entryTypes:
  - b9eaa895-752b-4102-8fac-49d7662c399d # Roles - Default
handle: roles
name: Roles
propagationMethod: all
siteSettings:
  1a69adf3-7129-4f03-a788-c50df99aa120: # Band Pioneer
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 80892bae-9aae-41c7-a024-7d86c870067a
type: structure
