defaultPlacement: end
enableVersioning: true
handle: roles
name: Roles
propagationMethod: all
siteSettings:
  1a69adf3-7129-4f03-a788-c50df99aa120: # Band Pioneer
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
